services:
  backend:
    build: ./backend
    container_name: minpol-backend
    ports:
      - "8000:8000"
    restart: unless-stopped

  frontend:
    build: ./ProyectoGUIFuentes
    container_name: minpol-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - ./ProyectoGUIFuentes:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    restart: unless-stopped
